server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.csc.spring.mybatis.annotation.domain
#  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    default-statement-timeout: 30


#logging:
#  level:
#    com.csc.springboot.mapper: DEBUG