server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      max-active: 20

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.csc.spring.mybatis.xml.domain
#  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    default-statement-timeout: 30
#    map-underscore-to-camel-case: true
#    object-factory:
#    environment:
#    database-id:
#  type-handlers-package:


#logging:
#  level:
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=counsql
#    com.csc.spring.mybatis.xml.mapper: DEBUG